### ISSUE TITLE
Blu robot players sometimes sliding when deploying (OfficerSpy himself asked me to post this issue)

### ISSUE THREAD

**Issue by Comicsanswich** [OfficerSpy/TF2-Be-With-Robots-Expanded-Enhanced#1]
OfficerSpy himself asked me to post this issue gonna he said I could post his clips if I wanted too I'm gonna also post my clips of the reduced tiny sliding.
Credits for the clips:
@OfficerSpy
[First clip](https://streamable.com/a7mmxb) and [Second clip](https://streamable.com/rnzidr)
@Comicsanswich
[First clip](https://file.garden/ZYzbz-L_DFdSLdFV/Team%20Fortress%202%20-%20Direct3D%209%20-%2064%20Bit%202024-08-22%2019-25-51.mp4) and [Second clip](https://file.garden/ZYzbz-L_DFdSLdFV/Team%20Fortress%202%20-%20Direct3D%209%20-%2064%20Bit%202024-08-22%2019-26-49.mp4)

**Comment by OfficerSpy** [comment]
Thinking about it, perhaps there was a better option if we just used `FL_FROZEN`. Would save the trouble of having to manually block inputs ourselves and won't make client prediction look so weird.
